### ISSUE TITLE
Summary does not update its data if there's no session refresh. 

### ISSUE THREAD

**Issue by cubismic** [CodeChain-io/codechain-explorer#110]
In the main page(Home.tsx), summary components do not update its data when there's no session refresh.

 This bug appeared from  https://github.com/CodeChain-io/codechain-explorer/commit/d8744c41db24b236f328cbd62b5abfaf760cf8d8 src/components/home/Summary/WeeklyChart.tsx : 45
```typescript
        if (data == null) {
            return <RequestWeeklyLogs type={type} onData={this.onData} onError={this.props.onError} />;
        }
````
The returning statement is the only part that changes its data and in the code.
Data will not be changed if it set once. 
So the condition should not be just `data == null`.

**Comment by joojis** [comment]
I'm closing this because we renewed the Summary component.
