### ISSUE TITLE
Uncomfortable to see "CCC" in the table

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain-explorer#116]
![image](https://user-images.githubusercontent.com/9711879/55932209-a6b66600-5c63-11e9-928e-6e086898f258.png)

Let's change the column header to something like Reward (CCC) and remove all the CCC in the data rows.

**Comment by cubismic** [comment]
@joojis. I think just moving CCC to the top is not the best idea. The users might confuse the unit.
I have three suggestions. I think spacing(give margin) is the best way. What do you think? 

![moving CCC](https://user-images.githubusercontent.com/31873152/55943245-2ef73400-5c81-11e9-91a9-0c6f5ecf4786.png)
![spacing](https://user-images.githubusercontent.com/31873152/55943255-33bbe800-5c81-11e9-972e-21bc4eb5120b.png)
![small font](https://user-images.githubusercontent.com/31873152/55943265-37e80580-5c81-11e9-8271-a4bac2376a3b.png)

**Comment by xpdlf1004** [comment]
I think the first is the best. And change it to the localeString.
