### ISSUE TITLE
Replace the loading bar with a spinner

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain-explorer#146]
- [x] Blocks page
  - list
- [x] Block page
  - tx list
- [x] Transactions page
  - list
- [x] Pending transactions page
  - list
- [x] Asset page
  - cap table
  - tx list
- [x] AssetAddress page
  - asset list
  - tx list
- [x] PlatformAddress page
  - balance history
  - tx list

**Comment by cubismic** [comment]
https://github.com/CodeChain-io/codechain-explorer/pull/147

**Comment by joojis** [comment]
https://github.com/CodeChain-io/codechain-explorer/pull/148
