### ISSUE TITLE
Show the detail of ChangeAssetScheme transaction

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain-explorer#60]
Current:
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/9711879/53060102-994eec00-34fc-11e9-9e52-6098e52d9e2f.png">

I think it should show the parameters of the new asset scheme.

- metadata
- approver
- administrator
- allowedScriptHashes

**Comment by cubismic** [comment]
https://github.com/CodeChain-io/codechain-explorer/pull/79
