### ISSUE TITLE
Explorer can not show `Order` information yet.

### ISSUE THREAD

**Issue by HoOngEe** [CodeChain-io/codechain-explorer#73]
For scenario tests on Corgi network, I have sent a lot of `assetTransferTransaction`s which have `orderOnTransfer` information. But the explorer is not supporting views for `orderOnTransfer` and `Order`. If it has the views for them, one can understand transactions related to orders more easily than before.

**Comment by cubismic** [comment]
https://github.com/CodeChain-io/codechain-explorer/pull/115
This patch might resolved this issue.
