### ISSUE TITLE
Explorer cannot find the user.

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain-explorer#76]
[wccqys3ds0rth9dz70wlacfhjzv7yql4s8r9vn95e3f](https://corgi.codechain.io/explorer/addr-platform/wccqys3ds0rth9dz70wlacfhjzv7yql4s8r9vn95e3f) is the signer of [0x6eb6d46eee052b86cb7b05f99368f8088b5e4b34b867c0bd8242705c6d2aedab](https://corgi.codechain.io/explorer/tx/0x6eb6d46eee052b86cb7b05f99368f8088b5e4b34b867c0bd8242705c6d2aedab), but the explorer cannot find the account page.

**Comment by xpdlf1004** [comment]
@joojis I think that It's a bug of the indexer.

**Comment by sgkim126** [comment]
@joojis I read the db manually, and there is no user in the db. It seems that it's a bug of the indexer.

**Comment by sgkim126** [comment]
I opened the issue on codechain-indexer. I'll close it.
