### ISSUE TITLE
TypeError: block.transactions is undefined

### ISSUE THREAD

**Issue by cubismic** [CodeChain-io/codechain-explorer#80]
There is no transactions field in the BlockDoc anymore. 

![Screenshot from 2019-03-29 14-03-32](https://user-images.githubusercontent.com/31873152/55210588-76b2a000-522b-11e9-9c8a-c9548deba3f3.png)

**Comment by joojis** [comment]
Fixed at https://github.com/CodeChain-io/codechain-explorer/pull/79
