### ISSUE TITLE
The list of transactions isn't shown in the block detail page

### ISSUE THREAD

**Issue by joojis** [CodeChain-io/codechain-explorer#83]

**Comment by sgkim126** [comment]
![before](https://user-images.githubusercontent.com/1138402/55373269-93a6e600-553f-11e9-8859-89a023678c02.png)

**Comment by sgkim126** [comment]
The number of transactions per type is also not updated.
![before](https://user-images.githubusercontent.com/1138402/55373330-c18c2a80-553f-11e9-9a64-7336ed9dcc3c.png)

**Comment by joojis** [comment]
<img width="1607" alt="image" src="https://user-images.githubusercontent.com/9711879/55462092-f88e3900-5630-11e9-859c-de96f08fc9e9.png">


https://explorer.codechain.io/block/24375
