### ISSUE TITLE
Some transaction types are not shown in the daily transaction pie chart

### ISSUE THREAD

**Issue by cubismic** [CodeChain-io/codechain-explorer#89]
src/request/RequestDailyLogs.ts

Currently, the pie chart only shows transaction counts of
[ mintAsset, transferAsset, composeAsset, decomposeAsset, pay, createShard, setRegularKey].

[ setRegularKey, setShardOwners, setShardUsers, changeAssetScheme, increaseAssetSupply, remove, custom, wrapCCC, unwrapCCC ]
Transaction types of above should be added.

**Comment by joojis** [comment]
I'm closing this because we don't show a pie chart for now.
