### ISSUE TITLE
Invalid representation for CCC

### ISSUE THREAD

**Issue by sgkim126** [CodeChain-io/codechain-explorer#97]
![ccc](https://user-images.githubusercontent.com/1138402/55548585-bdface00-570e-11e9-83cc-28995bd4f2af.png)

**Comment by joojis** [comment]
@xpdlf1004 Is it related to `CommaNumberString` component?

**Comment by joojis** [comment]
http://corgi.codechain.io/explorer/addr-platform/wccq83jt9vewlckstu84n7ek7spzcu9y4h23s3dsm7a

<img width="710" alt="image" src="https://user-images.githubusercontent.com/9711879/55605822-37e39380-57b1-11e9-9b81-0390e8516fd2.png">

This was fixed at https://github.com/CodeChain-io/codechain-explorer/commit/e2657cae94bd1cb5dbf6b22a0705d6e832104939 but I missed cherry-picking this patch in the corgi branch. Sorry.
